apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-example-app-nodejs-app-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: the-example-app-nodejs-app
        image: the-example-app.nodejs:latest
---
apiVersion: v1
kind: Service
metadata:
  name: the-example-app-nodejs-app-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001


